services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-container
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: horacio
      DB_PASSWORD: 12345678
      DB_NAME: ramori
    networks:
      - app-network


  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: ramori
      MYSQL_USER: horacio
      MYSQL_PASSWORD: 12345678
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
